# Generated by Django 4.1.5 on 2023-01-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chats',
        ),
    ]
